language: python

python: '3.7'

install:
- pip install -r requirements.txt
- pip install -e .

script:
  - export CONRAD_SKIP_POGS_CACHING_TESTS=1
  - nosetests conrad/tests/ --with-cover --cover-package=conrad

branches:
  only:
    - master
    - cvxpy_1.0
