language: python

python: '3.5.3'

install: 
  - sudo apt-get install libstdc++6
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test 
  - sudo apt-get update
  - sudo apt-get upgrade
  - sudo apt-get dist-upgrade
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda env create -f environment.yml
  - source activate test_env
  - pip install -e .

script: 
  - export CONRAD_SKIP_POGS_CACHING_TESTS=1
  - nosetests conrad/tests/ --with-cover --cover-package=conrad

branches:
  only:
    - master
    - old_cvx