name: test_env
channels:
  - conda-forge
  - cvxgrp
  - defaults
dependencies:
  - cloog==0.18.0
  - coverage==4.4.1
  - cvxpy==0.4.9
  - gcc==4.8.5
  - gmp==6.1.0
  - isl==0.12.2
  - lapack==3.6.1
  - libgfortran==3.0.0
  - mkl==2017.0.3
  - mpc==1.0.3
  - mpfr==3.1.5
  - nose==1.3.7
  - numpy==1.13.1
  - openssl==1.0.2l
  - pip==9.0.1
  - python==3.5.3
  - pyyaml==3.12
  - readline==6.2
  - scipy==0.19.1
  - setuptools==27.2.0
  - sqlite==3.13.0
  - tk==8.5.18
  - wheel==0.29.0
  - xz==5.2.2
  - yaml==0.1.6
  - zlib==1.2.8
  - pip:
    - ecos==2.0.4
    - scs==1.2.6
    - matplotlib==2.0.2